export const ADD_INGREDIENT = 'ADD_IMGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_IMGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PUCHASE_BURGER_START = 'PUCHASE_BURGER_START';
export const PUCHASE_BURGER_SUCCESS = 'PUCHASE_BURGER_SUCCESS';
export const PUCHASE_BURGER_FAIL = 'PUCHASE_BURGER_FAIL';